config/routes.rb
R4STechs::Application.routes.draw do
  resources :my_items

  resources :caarts

  get "cataloq/mycatalog"
  get "product_catalog/index"
  resources :components

  resources :line_items

  resources :carts
  get "catalog/MyCatalog"
  get "store/catalog"

  resources :store_products

  devise_for :users
  root  'static_pages#home'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contactus', to: 'static_pages#contactus', via: 'get'
  match '/account', to: 'static_pages#account', via: 'get'
  match '/shoppingCart', to: 'static_pages#shoppingCart', via: 'get'
  match '/login', to: 'static_pages#login', via: 'get'
  match '/component', to: 'component#components', via: 'get'
  match '/cataloq', to: 'cataloq#mycatalog', via: 'get'

end

app/models/adminuser.rb
class Adminuser < ActiveRecord::Base
	has_secure_password
  	validates_presence_of :password, :on => :create
end

app/models/caart.rb
class Caart < ActiveRecord::Base
	has_many :my_items, :dependent => :destroy

	def add_component(component_id)
		current_item = my_items.where(:component_id => component_id).first
			if current_item
				current_item.quantity += 1
			else
				current_item = MyItem.new(:component_id=>component_id)
				my_items << current_item
			end
		current_item
	end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, :dependent => :destroy

	def add_product(product_id)
		current_item = line_items.where(:product_id => product_id).first
			if current_item
				current_item.quantity += 1
			else
				current_item = LineItem.new(:product_id=>product_id)
				line_items << current_item
			end
		current_item
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/component.rb
class Component < ActiveRecord::Base
	validates :name, :description, :image_url, :presence => true
	validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
	has_many :my_items
	default_scope :order => 'name'
	before_destroy :ensure_not_referenced_by_any_my_item

	def ensure_not_referenced_by_any_my_item
		if my_items.count.zero?
		return true
		else
		errors[:base] << "My Items present"
		return false
	end
end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :product
	belongs_to :cart
end

app/models/my_item.rb
class MyItem < ActiveRecord::Base
	belongs_to :component
	belongs_to :caart
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :supplier
  belongs_to :category
end

app/models/store_product.rb
class StoreProduct < ActiveRecord::Base
	default_scope :order => 'name'
	has_many :line_items
	validates :name, :categoryid, :price , :quantity, :supplierid, :presence => true
	validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
	#validates :name, :uniqueness => true
	
	before_destroy :ensure_not_referenced_by_any_line_item

	# ensure that there are no line items referencing this product
	def ensure_not_referenced_by_any_line_item
		if line_items.count.zero?
		return true
		else
		errors[:base] << "Line Items present"
		return false
		end
	end
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
	has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/my_items_controller.rb
class MyItemsController < ApplicationController
  before_action :set_my_item, only: [:show, :edit, :update, :destroy]

  # GET /my_items
  # GET /my_items.json
  def index
    @my_items = MyItem.all
  end

  # GET /my_items/1
  # GET /my_items/1.json
  def show
  end

  # GET /my_items/new
  def new
    @my_item = MyItem.new
  end

  # GET /my_items/1/edit
  def edit
  end

  # POST /my_items
  # POST /my_items.json
  def create
    #@my_item = MyItem.new(my_item_params)

    @caart = current_caart
    component = Component.find(params[:component_id])
    @my_item = @caart.add_component(component.id)
    @my_item = @caart.my_items.build(:component => component)

    respond_to do |format|
      if @my_item.save
        format.html { redirect_to @my_item, notice: 'Line item was successfully added to cart.' }
        format.json { render action: 'show', status: :created, location: @my_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @my_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_items/1
  # PATCH/PUT /my_items/1.json
  def update
    respond_to do |format|
      if @my_item.update(my_item_params)
        format.html { redirect_to @my_item, notice: 'Line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @my_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_items/1
  # DELETE /my_items/1.json
  def destroy
    @my_item.destroy
    respond_to do |format|
      format.html { redirect_to my_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_item
      @my_item = MyItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_item_params
      params.require(:my_item).permit(:component_id, :caart_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caarts_helper.rb
module CaartsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/helpers/cataloq_helper.rb
module CataloqHelper
end

app/helpers/components_helper.rb
module ComponentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/my_items_helper.rb
module MyItemsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/my_items/_form.html.erb
<%= form_for(@my_item) do |f| %>
  <% if @my_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@my_item.errors.count, "error") %> prohibited this my_item from being saved:</h2>

      <ul>
      <% @my_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :component_id %><br>
    <%= f.number_field :component_id %>
  </div>
  <div class="field">
    <%= f.label :caart_id %><br>
    <%= f.number_field :caart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/my_items/edit.html.erb
<h1>Editing my_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @my_item %> |
<%= link_to 'Back', my_items_path %>

app/views/my_items/index.html.erb
<h1>Listing my_items</h1>

<table>
  <thead>
    <tr>
      <th>Component</th>
      <th>Caart</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @my_items.each do |my_item| %>
      <tr>
        <td><%= my_item.component_id %></td>
        <td><%= my_item.caart_id %></td>
        <td><%= link_to 'Show', my_item %></td>
        <td><%= link_to 'Edit', edit_my_item_path(my_item) %></td>
        <td><%= link_to 'Destroy', my_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My item', new_my_item_path %>

app/views/my_items/new.html.erb
<h1>New my_item</h1>

<%= render 'form' %>

<%= link_to 'Back', my_items_path %>

app/views/my_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Component:</strong>
  <%= @my_item.component_id %>
</p>

<p>
  <strong>Caart:</strong>
  <%= @my_item.caart_id %>
</p>

<%= link_to 'Edit', edit_my_item_path(@my_item) %> |
<%= link_to 'Back', my_items_path %>