config/routes.rb
R4STechs::Application.routes.draw do
  resources :my_items

  resources :caarts

  get "cataloq/mycatalog"
  get "product_catalog/index"
  resources :components

  resources :line_items

  resources :carts
  get "catalog/MyCatalog"
  get "store/catalog"

  resources :store_products

  devise_for :users
  root  'static_pages#home'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contactus', to: 'static_pages#contactus', via: 'get'
  match '/account', to: 'static_pages#account', via: 'get'
  match '/shoppingCart', to: 'static_pages#shoppingCart', via: 'get'
  match '/login', to: 'static_pages#login', via: 'get'
  match '/component', to: 'component#components', via: 'get'
  match '/cataloq', to: 'cataloq#mycatalog', via: 'get'

end

app/models/adminuser.rb
class Adminuser < ActiveRecord::Base
	has_secure_password
  	validates_presence_of :password, :on => :create
end

app/models/caart.rb
class Caart < ActiveRecord::Base
	has_many :my_items, :dependent => :destroy

	def add_component(component_id)
		current_item = my_items.where(:component_id => component_id).first
			if current_item
				current_item.quantity += 1
			else
				current_item = MyItem.new(:component_id=>component_id)
				my_items << current_item
			end
		current_item
	end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, :dependent => :destroy

	def add_product(product_id)
		current_item = line_items.where(:product_id => product_id).first
			if current_item
				current_item.quantity += 1
			else
				current_item = LineItem.new(:product_id=>product_id)
				line_items << current_item
			end
		current_item
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/component.rb
class Component < ActiveRecord::Base
	validates :name, :description, :image_url, :presence => true
	validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
	has_many :my_items
	default_scope :order => 'name'
	before_destroy :ensure_not_referenced_by_any_my_item

	def ensure_not_referenced_by_any_my_item
		if my_items.count.zero?
		return true
		else
		errors[:base] << "My Items present"
		return false
	end
end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :product
	belongs_to :cart
end

app/models/my_item.rb
class MyItem < ActiveRecord::Base
	belongs_to :component
	belongs_to :caart
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :supplier
  belongs_to :category
end

app/models/store_product.rb
class StoreProduct < ActiveRecord::Base
	default_scope :order => 'name'
	has_many :line_items
	validates :name, :categoryid, :price , :quantity, :supplierid, :presence => true
	validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
	#validates :name, :uniqueness => true
	
	before_destroy :ensure_not_referenced_by_any_line_item

	# ensure that there are no line items referencing this product
	def ensure_not_referenced_by_any_line_item
		if line_items.count.zero?
		return true
		else
		errors[:base] << "Line Items present"
		return false
		end
	end
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
	has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/store_products_controller.rb
class StoreProductsController < ApplicationController
  before_action :set_store_product, only: [:show, :edit, :update, :destroy]

  # GET /store_products
  # GET /store_products.json
  def index
    @store_products = StoreProduct.all
  end

  # GET /store_products/1
  # GET /store_products/1.json
  def show
  end

  # GET /store_products/new
  def new
    @store_product = StoreProduct.new
  end

  # GET /store_products/1/edit
  def edit
  end

  # POST /store_products
  # POST /store_products.json
  def create
    @store_product = StoreProduct.new(store_product_params)

    respond_to do |format|
      if @store_product.save
        format.html { redirect_to @store_product, notice: 'Store product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @store_product }
      else
        format.html { render action: 'new' }
        format.json { render json: @store_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /store_products/1
  # PATCH/PUT /store_products/1.json
  def update
    respond_to do |format|
      if @store_product.update(store_product_params)
        format.html { redirect_to @store_product, notice: 'Store product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @store_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /store_products/1
  # DELETE /store_products/1.json
  def destroy
    @store_product.destroy
    respond_to do |format|
      format.html { redirect_to store_products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store_product
      @store_product = StoreProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_product_params
      params.require(:store_product).permit(:name, :categoryid, :quantity, :supplierid, :image_url, :price)
    end
end

app/helpers/caarts_helper.rb
module CaartsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/helpers/cataloq_helper.rb
module CataloqHelper
end

app/helpers/components_helper.rb
module ComponentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/my_items_helper.rb
module MyItemsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/store_products_helper.rb
module StoreProductsHelper
end

app/views/store_products/_form.html.erb
<%= form_for(@store_product) do |f| %>
  <% if @store_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store_product.errors.count, "error") %> prohibited this store_product from being saved:</h2>

      <ul>
      <% @store_product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :categoryid %><br>
    <%= f.number_field :categoryid %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :supplierid %><br>
    <%= f.number_field :supplierid %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/store_products/edit.html.erb
<h1>Editing store_product</h1>

<%= render 'form' %>

<%= link_to 'Show', @store_product %> |
<%= link_to 'Back', store_products_path %>

app/views/store_products/index.html.erb
<h1>Listing store_products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Categoryid</th>
      <th>Quantity</th>
      <th>Supplierid</th>
      <th>Image url</th>
      <th>Price</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @store_products.each do |store_product| %>
      <tr>
        <td><%= store_product.name %></td>
        <td><%= store_product.categoryid %></td>
        <td><%= store_product.quantity %></td>
        <td><%= store_product.supplierid %></td>
        <td><%= store_product.image_url %></td>
        <td><%= store_product.price %></td>
        <td><%= link_to 'Show', store_product %></td>
        <td><%= link_to 'Edit', edit_store_product_path(store_product) %></td>
        <td><%= link_to 'Destroy', store_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Store product', new_store_product_path %>

app/views/store_products/new.html.erb
<h1>New store_product</h1>

<%= render 'form' %>

<%= link_to 'Back', store_products_path %>

app/views/store_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store_product.name %>
</p>

<p>
  <strong>Categoryid:</strong>
  <%= @store_product.categoryid %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @store_product.quantity %>
</p>

<p>
  <strong>Supplierid:</strong>
  <%= @store_product.supplierid %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @store_product.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @store_product.price %>
</p>

<%= link_to 'Edit', edit_store_product_path(@store_product) %> |
<%= link_to 'Back', store_products_path %>